// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createIMAPAccount = `-- name: CreateIMAPAccount :one
INSERT INTO accounts (
    workspace_id, display_name, email_address, auth_kind,
    imap_host, imap_port, smtp_host, smtp_port,
    secret_ref, fetch_since, sync_cadence_secs, ollama_model
) VALUES (?, ?, ?, 'imap', ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, display_name, email_address, auth_kind,
          imap_host, imap_port, smtp_host, smtp_port, secret_ref,
          fetch_since, sync_cadence_secs, last_synced_at, ollama_model,
          created_at, updated_at
`

type CreateIMAPAccountParams struct {
	WorkspaceID     int64
	DisplayName     string
	EmailAddress    string
	ImapHost        sql.NullString
	ImapPort        sql.NullInt64
	SmtpHost        sql.NullString
	SmtpPort        sql.NullInt64
	SecretRef       string
	FetchSince      sql.NullString
	SyncCadenceSecs int64
	OllamaModel     string
}

func (q *Queries) CreateIMAPAccount(ctx context.Context, arg CreateIMAPAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createIMAPAccount,
		arg.WorkspaceID,
		arg.DisplayName,
		arg.EmailAddress,
		arg.ImapHost,
		arg.ImapPort,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SecretRef,
		arg.FetchSince,
		arg.SyncCadenceSecs,
		arg.OllamaModel,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.EmailAddress,
		&i.AuthKind,
		&i.ImapHost,
		&i.ImapPort,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SecretRef,
		&i.FetchSince,
		&i.SyncCadenceSecs,
		&i.LastSyncedAt,
		&i.OllamaModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO accounts (
    workspace_id, display_name, email_address, auth_kind,
    secret_ref, fetch_since, sync_cadence_secs, ollama_model
) VALUES (?, ?, ?, 'gmail_oauth', ?, ?, ?, ?)
RETURNING id, workspace_id, display_name, email_address, auth_kind,
          imap_host, imap_port, smtp_host, smtp_port, secret_ref,
          fetch_since, sync_cadence_secs, last_synced_at, ollama_model,
          created_at, updated_at
`

type CreateOAuthAccountParams struct {
	WorkspaceID     int64
	DisplayName     string
	EmailAddress    string
	SecretRef       string
	FetchSince      sql.NullString
	SyncCadenceSecs int64
	OllamaModel     string
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createOAuthAccount,
		arg.WorkspaceID,
		arg.DisplayName,
		arg.EmailAddress,
		arg.SecretRef,
		arg.FetchSince,
		arg.SyncCadenceSecs,
		arg.OllamaModel,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.EmailAddress,
		&i.AuthKind,
		&i.ImapHost,
		&i.ImapPort,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SecretRef,
		&i.FetchSince,
		&i.SyncCadenceSecs,
		&i.LastSyncedAt,
		&i.OllamaModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, workspace_id, display_name, email_address, auth_kind,
       imap_host, imap_port, smtp_host, smtp_port, secret_ref,
       fetch_since, sync_cadence_secs, last_synced_at, ollama_model,
       created_at, updated_at
FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.EmailAddress,
		&i.AuthKind,
		&i.ImapHost,
		&i.ImapPort,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SecretRef,
		&i.FetchSince,
		&i.SyncCadenceSecs,
		&i.LastSyncedAt,
		&i.OllamaModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, workspace_id, display_name, email_address, auth_kind,
       imap_host, imap_port, smtp_host, smtp_port, secret_ref,
       fetch_since, sync_cadence_secs, last_synced_at, ollama_model,
       created_at, updated_at
FROM accounts
ORDER BY workspace_id, id
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DisplayName,
			&i.EmailAddress,
			&i.AuthKind,
			&i.ImapHost,
			&i.ImapPort,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SecretRef,
			&i.FetchSince,
			&i.SyncCadenceSecs,
			&i.LastSyncedAt,
			&i.OllamaModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByWorkspace = `-- name: ListAccountsByWorkspace :many
SELECT id, workspace_id, display_name, email_address, auth_kind,
       imap_host, imap_port, smtp_host, smtp_port, secret_ref,
       fetch_since, sync_cadence_secs, last_synced_at, ollama_model,
       created_at, updated_at
FROM accounts
WHERE workspace_id = ?
ORDER BY id
`

func (q *Queries) ListAccountsByWorkspace(ctx context.Context, workspaceID int64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DisplayName,
			&i.EmailAddress,
			&i.AuthKind,
			&i.ImapHost,
			&i.ImapPort,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SecretRef,
			&i.FetchSince,
			&i.SyncCadenceSecs,
			&i.LastSyncedAt,
			&i.OllamaModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountCadence = `-- name: UpdateAccountCadence :exec
UPDATE accounts
SET sync_cadence_secs = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateAccountCadenceParams struct {
	SyncCadenceSecs int64
	ID              int64
}

func (q *Queries) UpdateAccountCadence(ctx context.Context, arg UpdateAccountCadenceParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountCadence, arg.SyncCadenceSecs, arg.ID)
	return err
}

const updateAccountFetchSince = `-- name: UpdateAccountFetchSince :exec
UPDATE accounts
SET fetch_since = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateAccountFetchSinceParams struct {
	FetchSince sql.NullString
	ID         int64
}

func (q *Queries) UpdateAccountFetchSince(ctx context.Context, arg UpdateAccountFetchSinceParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountFetchSince, arg.FetchSince, arg.ID)
	return err
}

const updateAccountModel = `-- name: UpdateAccountModel :exec
UPDATE accounts
SET ollama_model = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateAccountModelParams struct {
	OllamaModel string
	ID          int64
}

func (q *Queries) UpdateAccountModel(ctx context.Context, arg UpdateAccountModelParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountModel, arg.OllamaModel, arg.ID)
	return err
}

const updateAccountSync = `-- name: UpdateAccountSync :exec
UPDATE accounts
SET last_synced_at = datetime('now'), updated_at = datetime('now')
WHERE id = ?
`

func (q *Queries) UpdateAccountSync(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateAccountSync, id)
	return err
}
