// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emails.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addEmailLabel = `-- name: AddEmailLabel :exec
INSERT INTO email_labels (email_id, label) VALUES (?, ?)
ON CONFLICT(email_id, label) DO NOTHING
`

type AddEmailLabelParams struct {
	EmailID int64
	Label   string
}

func (q *Queries) AddEmailLabel(ctx context.Context, arg AddEmailLabelParams) error {
	_, err := q.db.ExecContext(ctx, addEmailLabel, arg.EmailID, arg.Label)
	return err
}

const clearEmailLabels = `-- name: ClearEmailLabels :exec
DELETE FROM email_labels WHERE email_id = ?
`

func (q *Queries) ClearEmailLabels(ctx context.Context, emailID int64) error {
	_, err := q.db.ExecContext(ctx, clearEmailLabels, emailID)
	return err
}

const clearSnooze = `-- name: ClearSnooze :exec
UPDATE emails SET snoozed_until = NULL WHERE id = ?
`

func (q *Queries) ClearSnooze(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearSnooze, id)
	return err
}

const listDueSnoozed = `-- name: ListDueSnoozed :many
SELECT e.id, e.account_id, e.subject, e.snoozed_until,
       s.needs_attention, a.workspace_id
FROM emails e
JOIN accounts a ON a.id = e.account_id
LEFT JOIN summaries s ON s.email_id = e.id
WHERE e.snoozed_until IS NOT NULL AND e.snoozed_until <= ?
`

type ListDueSnoozedRow struct {
	ID             int64
	AccountID      int64
	Subject        string
	SnoozedUntil   sql.NullString
	NeedsAttention sql.NullInt64
	WorkspaceID    int64
}

// For the snooze ticker. Returns emails whose snoozed_until is <= now.
func (q *Queries) ListDueSnoozed(ctx context.Context, snoozedUntil sql.NullString) ([]ListDueSnoozedRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueSnoozed, snoozedUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueSnoozedRow{}
	for rows.Next() {
		var i ListDueSnoozedRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Subject,
			&i.SnoozedUntil,
			&i.NeedsAttention,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailLabels = `-- name: ListEmailLabels :many
SELECT label FROM email_labels WHERE email_id = ? ORDER BY label
`

func (q *Queries) ListEmailLabels(ctx context.Context, emailID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEmailLabels, emailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailsByAccount = `-- name: ListEmailsByAccount :many
SELECT e.id, e.account_id, e.message_id, e.folder, e.uid,
       e.from_address, e.from_name, e.to_addresses, e.cc_addresses,
       e.subject, e.received_at, e.body_plain, e.is_read, e.is_put_aside, e.category,
       COALESCE(s.summary, '')          AS summary,
       COALESCE(s.needs_attention, 0)   AS needs_attention,
       COALESCE(s.attention_reason, '') AS attention_reason
FROM emails e
LEFT JOIN summaries s ON s.email_id = e.id
WHERE e.account_id = ?
  AND (e.snoozed_until IS NULL OR e.snoozed_until <= datetime('now'))
ORDER BY e.received_at DESC
LIMIT ?
`

type ListEmailsByAccountParams struct {
	AccountID int64
	Limit     int64
}

type ListEmailsByAccountRow struct {
	ID              int64
	AccountID       int64
	MessageID       string
	Folder          string
	Uid             sql.NullInt64
	FromAddress     string
	FromName        string
	ToAddresses     string
	CcAddresses     string
	Subject         string
	ReceivedAt      string
	BodyPlain       string
	IsRead          int64
	IsPutAside      int64
	Category        string
	Summary         string
	NeedsAttention  int64
	AttentionReason string
}

func (q *Queries) ListEmailsByAccount(ctx context.Context, arg ListEmailsByAccountParams) ([]ListEmailsByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmailsByAccount, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailsByAccountRow{}
	for rows.Next() {
		var i ListEmailsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.MessageID,
			&i.Folder,
			&i.Uid,
			&i.FromAddress,
			&i.FromName,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.Subject,
			&i.ReceivedAt,
			&i.BodyPlain,
			&i.IsRead,
			&i.IsPutAside,
			&i.Category,
			&i.Summary,
			&i.NeedsAttention,
			&i.AttentionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailsByThread = `-- name: ListEmailsByThread :many
SELECT id, account_id, from_address, from_name, subject, received_at,
       body_plain, is_read, is_put_aside, category
FROM emails
WHERE thread_id = ?
ORDER BY received_at ASC
`

type ListEmailsByThreadRow struct {
	ID          int64
	AccountID   int64
	FromAddress string
	FromName    string
	Subject     string
	ReceivedAt  string
	BodyPlain   string
	IsRead      int64
	IsPutAside  int64
	Category    string
}

func (q *Queries) ListEmailsByThread(ctx context.Context, threadID string) ([]ListEmailsByThreadRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmailsByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailsByThreadRow{}
	for rows.Next() {
		var i ListEmailsByThreadRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.FromAddress,
			&i.FromName,
			&i.Subject,
			&i.ReceivedAt,
			&i.BodyPlain,
			&i.IsRead,
			&i.IsPutAside,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailsByWorkspace = `-- name: ListEmailsByWorkspace :many
SELECT e.id, e.account_id, e.message_id, e.folder, e.uid,
       e.from_address, e.from_name, e.to_addresses, e.cc_addresses,
       e.subject, e.received_at, e.body_plain, e.is_read, e.is_put_aside, e.category,
       COALESCE(s.summary, '')          AS summary,
       COALESCE(s.needs_attention, 0)   AS needs_attention,
       COALESCE(s.attention_reason, '') AS attention_reason
FROM emails e
JOIN accounts a ON a.id = e.account_id
LEFT JOIN summaries s ON s.email_id = e.id
WHERE a.workspace_id = ?
  AND (e.snoozed_until IS NULL OR e.snoozed_until <= datetime('now'))
ORDER BY e.received_at DESC
LIMIT ?
`

type ListEmailsByWorkspaceParams struct {
	WorkspaceID int64
	Limit       int64
}

type ListEmailsByWorkspaceRow struct {
	ID              int64
	AccountID       int64
	MessageID       string
	Folder          string
	Uid             sql.NullInt64
	FromAddress     string
	FromName        string
	ToAddresses     string
	CcAddresses     string
	Subject         string
	ReceivedAt      string
	BodyPlain       string
	IsRead          int64
	IsPutAside      int64
	Category        string
	Summary         string
	NeedsAttention  int64
	AttentionReason string
}

func (q *Queries) ListEmailsByWorkspace(ctx context.Context, arg ListEmailsByWorkspaceParams) ([]ListEmailsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmailsByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailsByWorkspaceRow{}
	for rows.Next() {
		var i ListEmailsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.MessageID,
			&i.Folder,
			&i.Uid,
			&i.FromAddress,
			&i.FromName,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.Subject,
			&i.ReceivedAt,
			&i.BodyPlain,
			&i.IsRead,
			&i.IsPutAside,
			&i.Category,
			&i.Summary,
			&i.NeedsAttention,
			&i.AttentionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNeedsAttentionSince = `-- name: ListNeedsAttentionSince :many
SELECT e.id, e.account_id, e.from_address, e.from_name, e.subject,
       e.received_at, s.summary, s.attention_reason, a.workspace_id
FROM emails e
JOIN summaries s ON s.email_id = e.id
JOIN accounts a ON a.id = e.account_id
WHERE s.needs_attention = 1
  AND s.generated_at >= ?
ORDER BY e.received_at DESC
`

type ListNeedsAttentionSinceRow struct {
	ID              int64
	AccountID       int64
	FromAddress     string
	FromName        string
	Subject         string
	ReceivedAt      string
	Summary         string
	AttentionReason string
	WorkspaceID     int64
}

func (q *Queries) ListNeedsAttentionSince(ctx context.Context, generatedAt string) ([]ListNeedsAttentionSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listNeedsAttentionSince, generatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNeedsAttentionSinceRow{}
	for rows.Next() {
		var i ListNeedsAttentionSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.FromAddress,
			&i.FromName,
			&i.Subject,
			&i.ReceivedAt,
			&i.Summary,
			&i.AttentionReason,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnoozedByWorkspace = `-- name: ListSnoozedByWorkspace :many
SELECT e.id, e.account_id, e.from_address, e.from_name, e.subject,
       e.received_at, e.snoozed_until
FROM emails e
JOIN accounts a ON a.id = e.account_id
WHERE a.workspace_id = ? AND e.snoozed_until IS NOT NULL
ORDER BY e.snoozed_until ASC
`

type ListSnoozedByWorkspaceRow struct {
	ID           int64
	AccountID    int64
	FromAddress  string
	FromName     string
	Subject      string
	ReceivedAt   string
	SnoozedUntil sql.NullString
}

func (q *Queries) ListSnoozedByWorkspace(ctx context.Context, workspaceID int64) ([]ListSnoozedByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnoozedByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnoozedByWorkspaceRow{}
	for rows.Next() {
		var i ListSnoozedByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.FromAddress,
			&i.FromName,
			&i.Subject,
			&i.ReceivedAt,
			&i.SnoozedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailRead = `-- name: MarkEmailRead :exec
UPDATE emails SET is_read = 1 WHERE id = ?
`

func (q *Queries) MarkEmailRead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEmailRead, id)
	return err
}

const markEmailUnread = `-- name: MarkEmailUnread :exec
UPDATE emails SET is_read = 0 WHERE id = ?
`

func (q *Queries) MarkEmailUnread(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEmailUnread, id)
	return err
}

const maxUIDForFolder = `-- name: MaxUIDForFolder :one
SELECT CAST(COALESCE(MAX(uid), 0) AS INTEGER) AS max_uid
FROM emails
WHERE account_id = ? AND folder = ?
`

type MaxUIDForFolderParams struct {
	AccountID int64
	Folder    string
}

func (q *Queries) MaxUIDForFolder(ctx context.Context, arg MaxUIDForFolderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxUIDForFolder, arg.AccountID, arg.Folder)
	var max_uid int64
	err := row.Scan(&max_uid)
	return max_uid, err
}

const setCategory = `-- name: SetCategory :exec
UPDATE emails SET category = ? WHERE id = ?
`

type SetCategoryParams struct {
	Category string
	ID       int64
}

func (q *Queries) SetCategory(ctx context.Context, arg SetCategoryParams) error {
	_, err := q.db.ExecContext(ctx, setCategory, arg.Category, arg.ID)
	return err
}

const setSnooze = `-- name: SetSnooze :exec
UPDATE emails SET snoozed_until = ? WHERE id = ?
`

type SetSnoozeParams struct {
	SnoozedUntil sql.NullString
	ID           int64
}

func (q *Queries) SetSnooze(ctx context.Context, arg SetSnoozeParams) error {
	_, err := q.db.ExecContext(ctx, setSnooze, arg.SnoozedUntil, arg.ID)
	return err
}

const togglePutAside = `-- name: TogglePutAside :exec
UPDATE emails SET is_put_aside = 1 - is_put_aside WHERE id = ?
`

func (q *Queries) TogglePutAside(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, togglePutAside, id)
	return err
}

const upsertEmail = `-- name: UpsertEmail :one
INSERT INTO emails (
    account_id, message_id, folder, uid,
    from_address, from_name, to_addresses, cc_addresses,
    subject, received_at, body_plain, body_html, headers_json,
    in_reply_to, email_refs, thread_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(account_id, message_id) DO UPDATE SET
    folder       = excluded.folder,
    uid          = excluded.uid,
    body_plain   = excluded.body_plain,
    body_html    = excluded.body_html,
    headers_json = excluded.headers_json,
    in_reply_to  = excluded.in_reply_to,
    email_refs   = excluded.email_refs,
    thread_id    = excluded.thread_id
RETURNING id
`

type UpsertEmailParams struct {
	AccountID   int64
	MessageID   string
	Folder      string
	Uid         sql.NullInt64
	FromAddress string
	FromName    string
	ToAddresses string
	CcAddresses string
	Subject     string
	ReceivedAt  string
	BodyPlain   string
	BodyHtml    string
	HeadersJson string
	InReplyTo   string
	EmailRefs   string
	ThreadID    string
}

func (q *Queries) UpsertEmail(ctx context.Context, arg UpsertEmailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertEmail,
		arg.AccountID,
		arg.MessageID,
		arg.Folder,
		arg.Uid,
		arg.FromAddress,
		arg.FromName,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.Subject,
		arg.ReceivedAt,
		arg.BodyPlain,
		arg.BodyHtml,
		arg.HeadersJson,
		arg.InReplyTo,
		arg.EmailRefs,
		arg.ThreadID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
