// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emails.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const listEmailsByAccount = `-- name: ListEmailsByAccount :many
SELECT id, account_id, message_id, folder, uid,
       from_address, from_name, to_addresses, cc_addresses,
       subject, received_at, body_plain, is_read, is_put_aside, category
FROM emails
WHERE account_id = ?
ORDER BY received_at DESC
LIMIT ?
`

type ListEmailsByAccountParams struct {
	AccountID int64
	Limit     int64
}

type ListEmailsByAccountRow struct {
	ID          int64
	AccountID   int64
	MessageID   string
	Folder      string
	Uid         sql.NullInt64
	FromAddress string
	FromName    string
	ToAddresses string
	CcAddresses string
	Subject     string
	ReceivedAt  string
	BodyPlain   string
	IsRead      int64
	IsPutAside  int64
	Category    string
}

func (q *Queries) ListEmailsByAccount(ctx context.Context, arg ListEmailsByAccountParams) ([]ListEmailsByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmailsByAccount, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailsByAccountRow{}
	for rows.Next() {
		var i ListEmailsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.MessageID,
			&i.Folder,
			&i.Uid,
			&i.FromAddress,
			&i.FromName,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.Subject,
			&i.ReceivedAt,
			&i.BodyPlain,
			&i.IsRead,
			&i.IsPutAside,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailsByWorkspace = `-- name: ListEmailsByWorkspace :many
SELECT e.id, e.account_id, e.message_id, e.folder, e.uid,
       e.from_address, e.from_name, e.to_addresses, e.cc_addresses,
       e.subject, e.received_at, e.body_plain, e.is_read, e.is_put_aside, e.category
FROM emails e
JOIN accounts a ON a.id = e.account_id
WHERE a.workspace_id = ?
ORDER BY e.received_at DESC
LIMIT ?
`

type ListEmailsByWorkspaceParams struct {
	WorkspaceID int64
	Limit       int64
}

type ListEmailsByWorkspaceRow struct {
	ID          int64
	AccountID   int64
	MessageID   string
	Folder      string
	Uid         sql.NullInt64
	FromAddress string
	FromName    string
	ToAddresses string
	CcAddresses string
	Subject     string
	ReceivedAt  string
	BodyPlain   string
	IsRead      int64
	IsPutAside  int64
	Category    string
}

func (q *Queries) ListEmailsByWorkspace(ctx context.Context, arg ListEmailsByWorkspaceParams) ([]ListEmailsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmailsByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailsByWorkspaceRow{}
	for rows.Next() {
		var i ListEmailsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.MessageID,
			&i.Folder,
			&i.Uid,
			&i.FromAddress,
			&i.FromName,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.Subject,
			&i.ReceivedAt,
			&i.BodyPlain,
			&i.IsRead,
			&i.IsPutAside,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNeedsAttentionSince = `-- name: ListNeedsAttentionSince :many
SELECT e.id, e.account_id, e.from_address, e.from_name, e.subject,
       e.received_at, s.summary, s.attention_reason, a.workspace_id
FROM emails e
JOIN summaries s ON s.email_id = e.id
JOIN accounts a ON a.id = e.account_id
WHERE s.needs_attention = 1
  AND s.generated_at >= ?
ORDER BY e.received_at DESC
`

type ListNeedsAttentionSinceRow struct {
	ID              int64
	AccountID       int64
	FromAddress     string
	FromName        string
	Subject         string
	ReceivedAt      string
	Summary         string
	AttentionReason string
	WorkspaceID     int64
}

func (q *Queries) ListNeedsAttentionSince(ctx context.Context, generatedAt string) ([]ListNeedsAttentionSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listNeedsAttentionSince, generatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNeedsAttentionSinceRow{}
	for rows.Next() {
		var i ListNeedsAttentionSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.FromAddress,
			&i.FromName,
			&i.Subject,
			&i.ReceivedAt,
			&i.Summary,
			&i.AttentionReason,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailRead = `-- name: MarkEmailRead :exec
UPDATE emails SET is_read = 1 WHERE id = ?
`

func (q *Queries) MarkEmailRead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEmailRead, id)
	return err
}

const markEmailUnread = `-- name: MarkEmailUnread :exec
UPDATE emails SET is_read = 0 WHERE id = ?
`

func (q *Queries) MarkEmailUnread(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEmailUnread, id)
	return err
}

const maxUIDForFolder = `-- name: MaxUIDForFolder :one
SELECT CAST(COALESCE(MAX(uid), 0) AS INTEGER) AS max_uid
FROM emails
WHERE account_id = ? AND folder = ?
`

type MaxUIDForFolderParams struct {
	AccountID int64
	Folder    string
}

func (q *Queries) MaxUIDForFolder(ctx context.Context, arg MaxUIDForFolderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxUIDForFolder, arg.AccountID, arg.Folder)
	var max_uid int64
	err := row.Scan(&max_uid)
	return max_uid, err
}

const setCategory = `-- name: SetCategory :exec
UPDATE emails SET category = ? WHERE id = ?
`

type SetCategoryParams struct {
	Category string
	ID       int64
}

func (q *Queries) SetCategory(ctx context.Context, arg SetCategoryParams) error {
	_, err := q.db.ExecContext(ctx, setCategory, arg.Category, arg.ID)
	return err
}

const togglePutAside = `-- name: TogglePutAside :exec
UPDATE emails SET is_put_aside = 1 - is_put_aside WHERE id = ?
`

func (q *Queries) TogglePutAside(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, togglePutAside, id)
	return err
}

const upsertEmail = `-- name: UpsertEmail :one
INSERT INTO emails (
    account_id, message_id, folder, uid,
    from_address, from_name, to_addresses, cc_addresses,
    subject, received_at, body_plain, body_html, headers_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(account_id, message_id) DO UPDATE SET
    folder       = excluded.folder,
    uid          = excluded.uid,
    body_plain   = excluded.body_plain,
    body_html    = excluded.body_html,
    headers_json = excluded.headers_json
RETURNING id
`

type UpsertEmailParams struct {
	AccountID   int64
	MessageID   string
	Folder      string
	Uid         sql.NullInt64
	FromAddress string
	FromName    string
	ToAddresses string
	CcAddresses string
	Subject     string
	ReceivedAt  string
	BodyPlain   string
	BodyHtml    string
	HeadersJson string
}

func (q *Queries) UpsertEmail(ctx context.Context, arg UpsertEmailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertEmail,
		arg.AccountID,
		arg.MessageID,
		arg.Folder,
		arg.Uid,
		arg.FromAddress,
		arg.FromName,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.Subject,
		arg.ReceivedAt,
		arg.BodyPlain,
		arg.BodyHtml,
		arg.HeadersJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
