// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Account struct {
	ID              int64
	WorkspaceID     int64
	DisplayName     string
	EmailAddress    string
	AuthKind        string
	ImapHost        sql.NullString
	ImapPort        sql.NullInt64
	SmtpHost        sql.NullString
	SmtpPort        sql.NullInt64
	SecretRef       string
	FetchSince      sql.NullString
	SyncCadenceSecs int64
	LastSyncedAt    sql.NullString
	OllamaModel     string
	FolderAllowlist string
	CreatedAt       string
	UpdatedAt       string
}

type AccountRecipient struct {
	AccountID   int64
	RecipientID int64
}

type AppSetting struct {
	ID           int64
	OllamaUrl    string
	DefaultModel string
}

type Email struct {
	ID          int64
	AccountID   int64
	MessageID   string
	Folder      string
	Uid         sql.NullInt64
	FromAddress string
	FromName    string
	ToAddresses string
	CcAddresses string
	Subject     string
	ReceivedAt  string
	BodyPlain   string
	BodyHtml    string
	HeadersJson string
	IsRead      int64
	IsPutAside  int64
	Category    string
	CreatedAt   string
}

type EmailsFt struct {
	Subject   string
	BodyPlain string
}

type FilterRule struct {
	ID        int64
	AccountID int64
	Kind      string
	Pattern   string
	Reason    string
	CreatedAt string
}

type Sender struct {
	ID            int64
	AccountID     int64
	Address       string
	ScreenerState string
	FirstSeenAt   string
}

type Summary struct {
	EmailID         int64
	Summary         string
	NeedsAttention  int64
	AttentionReason string
	Model           string
	GeneratedAt     string
}

type TelegramRecipient struct {
	ID        int64
	Name      string
	ChatID    string
	CreatedAt string
}

type TelegramSetting struct {
	ID         int64
	BotToken   string
	DigestTime string
}

type Workspace struct {
	ID        int64
	Name      string
	Emoji     string
	SortOrder int64
	CreatedAt string
	UpdatedAt string
}

type WorkspaceRecipient struct {
	WorkspaceID int64
	RecipientID int64
}
