// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planner.sql

package sqlcgen

import (
	"context"
)

const createCalendarBlock = `-- name: CreateCalendarBlock :one
C;

INSERT INTO calendar_blocks (workspace_id, title, notes, start_at, end_at, kind)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, title, notes, start_at, end_at, kind,
          google_event_id, created_at, updated_
`

type CreateCalendarBlockParams struct {
	WorkspaceID int64
	Title       string
	Notes       string
	StartAt     string
	EndAt       string
	Kind        string
}

func (q *Queries) CreateCalendarBlock(ctx context.Context, arg CreateCalendarBlockParams) (CalendarBlock, error) {
	row := q.db.QueryRowContext(ctx, createCalendarBlock,
		arg.WorkspaceID,
		arg.Title,
		arg.Notes,
		arg.StartAt,
		arg.EndAt,
		arg.Kind,
	)
	var i CalendarBlock
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Notes,
		&i.StartAt,
		&i.EndAt,
		&i.Kind,
		&i.GoogleEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNote = `-- name: CreateNote :one
?;

INSERT INTO notes (workspace_id, title, body_md)
VALUES (?, ?, ?)
RETURNING id, workspace_id, title, body_md, created_at, updated_
`

type CreateNoteParams struct {
	WorkspaceID int64
	Title       string
	BodyMd      string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.WorkspaceID, arg.Title, arg.BodyMd)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.BodyMd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTodo = `-- name: CreateTodo :one
?;

INSERT INTO todos (workspace_id, text, due_at, sort_order)
VALUES (?, ?, ?, ?)
RETURNING id, workspace_id, text, done, due_at, sort_order, created_at, updated_
`

type CreateTodoParams struct {
	WorkspaceID int64
	Text        string
	DueAt       string
	SortOrder   int64
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.WorkspaceID,
		arg.Text,
		arg.DueAt,
		arg.SortOrder,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Text,
		&i.Done,
		&i.DueAt,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCalendarBlock = `-- name: DeleteCalendarBlock :exec
?;

DELETE FROM calendar_blocks WHERE id =
`

func (q *Queries) DeleteCalendarBlock(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCalendarBlock, id)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
?;

DELETE FROM notes WHERE id =
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
?;

DELETE FROM todos WHERE id =
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getNote = `-- name: GetNote :one
C;

SELECT id, workspace_id, title, body_md, created_at, updated_at
FROM notes WHERE id =
`

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.BodyMd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCalendarBlocks = `-- name: ListCalendarBlocks :many

SELECT id, workspace_id, title, notes, start_at, end_at, kind,
       google_event_id, created_at, updated_at
FROM calendar_blocks
WHERE workspace_id = ? AND end_at >= ?
ORDER BY start_at A
`

type ListCalendarBlocksParams struct {
	WorkspaceID int64
	EndAt       string
}

// Calendar blocks, todos, and notes — the "planner" surface area for each
// workspace. All three are workspace-scoped; nothing here syncs externally
// until the calendar promotion path lands.
func (q *Queries) ListCalendarBlocks(ctx context.Context, arg ListCalendarBlocksParams) ([]CalendarBlock, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarBlocks, arg.WorkspaceID, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarBlock{}
	for rows.Next() {
		var i CalendarBlock
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Notes,
			&i.StartAt,
			&i.EndAt,
			&i.Kind,
			&i.GoogleEventID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotes = `-- name: ListNotes :many
?;

SELECT id, workspace_id, title, body_md, created_at, updated_at
FROM notes
WHERE workspace_id = ?
ORDER BY updated_at DE
`

func (q *Queries) ListNotes(ctx context.Context, workspaceID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.BodyMd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
?;

SELECT id, workspace_id, text, done, due_at, sort_order, created_at, updated_at
FROM todos
WHERE workspace_id = ?
ORDER BY done ASC, sort_order ASC, id A
`

func (q *Queries) ListTodos(ctx context.Context, workspaceID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Text,
			&i.Done,
			&i.DueAt,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTodoSort = `-- name: NextTodoSort :one
C;

SELECT CAST(COALESCE(MAX(sort_order) + 1, 0) AS INTEGER) AS next_sort
FROM todos WHERE workspace_id =
`

func (q *Queries) NextTodoSort(ctx context.Context, workspaceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextTodoSort, workspaceID)
	var next_sort int64
	err := row.Scan(&next_sort)
	return next_sort, err
}

const setCalendarGoogleEvent = `-- name: SetCalendarGoogleEvent :exec
?;

UPDATE calendar_blocks SET google_event_id = ?, updated_at = datetime('now')
WHERE id =
`

type SetCalendarGoogleEventParams struct {
	GoogleEventID string
	ID            int64
}

func (q *Queries) SetCalendarGoogleEvent(ctx context.Context, arg SetCalendarGoogleEventParams) error {
	_, err := q.db.ExecContext(ctx, setCalendarGoogleEvent, arg.GoogleEventID, arg.ID)
	return err
}

const setTodoDone = `-- name: SetTodoDone :exec
?;

UPDATE todos SET done = ?, updated_at = datetime('now') WHERE id =
`

type SetTodoDoneParams struct {
	Done int64
	ID   int64
}

func (q *Queries) SetTodoDone(ctx context.Context, arg SetTodoDoneParams) error {
	_, err := q.db.ExecContext(ctx, setTodoDone, arg.Done, arg.ID)
	return err
}

const updateCalendarBlock = `-- name: UpdateCalendarBlock :exec
t;

UPDATE calendar_blocks
SET title = ?, notes = ?, start_at = ?, end_at = ?, kind = ?,
    updated_at = datetime('now')
WHERE id =
`

type UpdateCalendarBlockParams struct {
	Title   string
	Notes   string
	StartAt string
	EndAt   string
	Kind    string
	ID      int64
}

func (q *Queries) UpdateCalendarBlock(ctx context.Context, arg UpdateCalendarBlockParams) error {
	_, err := q.db.ExecContext(ctx, updateCalendarBlock,
		arg.Title,
		arg.Notes,
		arg.StartAt,
		arg.EndAt,
		arg.Kind,
		arg.ID,
	)
	return err
}

const updateNote = `-- name: UpdateNote :exec
t;

UPDATE notes SET title = ?, body_md = ?, updated_at = datetime('now')
WHERE id =
`

type UpdateNoteParams struct {
	Title  string
	BodyMd string
	ID     int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateNote, arg.Title, arg.BodyMd, arg.ID)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
t;

UPDATE todos
SET text = ?, due_at = ?, done = ?, updated_at = datetime('now')
WHERE id =
`

type UpdateTodoParams struct {
	Text  string
	DueAt string
	Done  int64
	ID    int64
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo,
		arg.Text,
		arg.DueAt,
		arg.Done,
		arg.ID,
	)
	return err
}
