// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summaries.sql

package sqlcgen

import (
	"context"
)

const getAccountModel = `-- name: GetAccountModel :one
SELECT a.ollama_model AS account_model,
       s.default_model AS default_model
FROM accounts a, app_settings s
WHERE a.id = ? AND s.id = 1
`

type GetAccountModelRow struct {
	AccountModel string
	DefaultModel string
}

func (q *Queries) GetAccountModel(ctx context.Context, id int64) (GetAccountModelRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountModel, id)
	var i GetAccountModelRow
	err := row.Scan(&i.AccountModel, &i.DefaultModel)
	return i, err
}

const getSummaryForEmail = `-- name: GetSummaryForEmail :one
SELECT email_id, summary, needs_attention, attention_reason, model, generated_at
FROM summaries
WHERE email_id = ?
`

func (q *Queries) GetSummaryForEmail(ctx context.Context, emailID int64) (Summary, error) {
	row := q.db.QueryRowContext(ctx, getSummaryForEmail, emailID)
	var i Summary
	err := row.Scan(
		&i.EmailID,
		&i.Summary,
		&i.NeedsAttention,
		&i.AttentionReason,
		&i.Model,
		&i.GeneratedAt,
	)
	return i, err
}

const listUnsummarizedByAccount = `-- name: ListUnsummarizedByAccount :many
SELECT e.id, e.from_address, e.from_name, e.subject, e.received_at, e.body_plain
FROM emails e
LEFT JOIN summaries s ON s.email_id = e.id
WHERE e.account_id = ?
  AND s.email_id IS NULL
ORDER BY e.received_at DESC
LIMIT ?
`

type ListUnsummarizedByAccountParams struct {
	AccountID int64
	Limit     int64
}

type ListUnsummarizedByAccountRow struct {
	ID          int64
	FromAddress string
	FromName    string
	Subject     string
	ReceivedAt  string
	BodyPlain   string
}

func (q *Queries) ListUnsummarizedByAccount(ctx context.Context, arg ListUnsummarizedByAccountParams) ([]ListUnsummarizedByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnsummarizedByAccount, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnsummarizedByAccountRow{}
	for rows.Next() {
		var i ListUnsummarizedByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.FromAddress,
			&i.FromName,
			&i.Subject,
			&i.ReceivedAt,
			&i.BodyPlain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSummary = `-- name: UpsertSummary :exec
INSERT INTO summaries (email_id, summary, needs_attention, attention_reason, model)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(email_id) DO UPDATE SET
    summary          = excluded.summary,
    needs_attention  = excluded.needs_attention,
    attention_reason = excluded.attention_reason,
    model            = excluded.model,
    generated_at     = datetime('now')
`

type UpsertSummaryParams struct {
	EmailID         int64
	Summary         string
	NeedsAttention  int64
	AttentionReason string
	Model           string
}

func (q *Queries) UpsertSummary(ctx context.Context, arg UpsertSummaryParams) error {
	_, err := q.db.ExecContext(ctx, upsertSummary,
		arg.EmailID,
		arg.Summary,
		arg.NeedsAttention,
		arg.AttentionReason,
		arg.Model,
	)
	return err
}
