// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram.sql

package sqlcgen

import (
	"context"
)

const assignRecipientToAccount = `-- name: AssignRecipientToAccount :exec
INSERT OR IGNORE INTO account_recipients (account_id, recipient_id) VALUES (?, ?)
`

type AssignRecipientToAccountParams struct {
	AccountID   int64
	RecipientID int64
}

func (q *Queries) AssignRecipientToAccount(ctx context.Context, arg AssignRecipientToAccountParams) error {
	_, err := q.db.ExecContext(ctx, assignRecipientToAccount, arg.AccountID, arg.RecipientID)
	return err
}

const assignRecipientToWorkspace = `-- name: AssignRecipientToWorkspace :exec
INSERT OR IGNORE INTO workspace_recipients (workspace_id, recipient_id) VALUES (?, ?)
`

type AssignRecipientToWorkspaceParams struct {
	WorkspaceID int64
	RecipientID int64
}

func (q *Queries) AssignRecipientToWorkspace(ctx context.Context, arg AssignRecipientToWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, assignRecipientToWorkspace, arg.WorkspaceID, arg.RecipientID)
	return err
}

const createRecipient = `-- name: CreateRecipient :one
INSERT INTO telegram_recipients (name, chat_id) VALUES (?, ?)
RETURNING id, name, chat_id, created_at
`

type CreateRecipientParams struct {
	Name   string
	ChatID string
}

func (q *Queries) CreateRecipient(ctx context.Context, arg CreateRecipientParams) (TelegramRecipient, error) {
	row := q.db.QueryRowContext(ctx, createRecipient, arg.Name, arg.ChatID)
	var i TelegramRecipient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChatID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecipient = `-- name: DeleteRecipient :exec
DELETE FROM telegram_recipients WHERE id = ?
`

func (q *Queries) DeleteRecipient(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecipient, id)
	return err
}

const getTelegramSettings = `-- name: GetTelegramSettings :one
SELECT bot_token, digest_time FROM telegram_settings WHERE id = 1
`

type GetTelegramSettingsRow struct {
	BotToken   string
	DigestTime string
}

func (q *Queries) GetTelegramSettings(ctx context.Context) (GetTelegramSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getTelegramSettings)
	var i GetTelegramSettingsRow
	err := row.Scan(&i.BotToken, &i.DigestTime)
	return i, err
}

const listRecipients = `-- name: ListRecipients :many
SELECT id, name, chat_id, created_at
FROM telegram_recipients
ORDER BY name
`

func (q *Queries) ListRecipients(ctx context.Context) ([]TelegramRecipient, error) {
	rows, err := q.db.QueryContext(ctx, listRecipients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelegramRecipient{}
	for rows.Next() {
		var i TelegramRecipient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ChatID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipientsForAccount = `-- name: ListRecipientsForAccount :many
SELECT r.id, r.name, r.chat_id
FROM telegram_recipients r
JOIN account_recipients ar ON ar.recipient_id = r.id
WHERE ar.account_id = ?
`

type ListRecipientsForAccountRow struct {
	ID     int64
	Name   string
	ChatID string
}

func (q *Queries) ListRecipientsForAccount(ctx context.Context, accountID int64) ([]ListRecipientsForAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipientsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipientsForAccountRow{}
	for rows.Next() {
		var i ListRecipientsForAccountRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ChatID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipientsForFanout = `-- name: ListRecipientsForFanout :many
SELECT DISTINCT r.id, r.name, r.chat_id
FROM telegram_recipients r
WHERE r.id IN (
    SELECT wr.recipient_id
    FROM workspace_recipients wr
    JOIN accounts a ON a.workspace_id = wr.workspace_id
    WHERE a.id = ?1
    UNION
    SELECT ar.recipient_id
    FROM account_recipients ar
    WHERE ar.account_id = ?1
)
`

type ListRecipientsForFanoutRow struct {
	ID     int64
	Name   string
	ChatID string
}

// Combined fan-out: union of workspace and account assignments for a
// given account, so callers can fire a notify with one query.
func (q *Queries) ListRecipientsForFanout(ctx context.Context, accountID int64) ([]ListRecipientsForFanoutRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipientsForFanout, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipientsForFanoutRow{}
	for rows.Next() {
		var i ListRecipientsForFanoutRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ChatID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipientsForWorkspace = `-- name: ListRecipientsForWorkspace :many
SELECT r.id, r.name, r.chat_id
FROM telegram_recipients r
JOIN workspace_recipients wr ON wr.recipient_id = r.id
WHERE wr.workspace_id = ?
`

type ListRecipientsForWorkspaceRow struct {
	ID     int64
	Name   string
	ChatID string
}

func (q *Queries) ListRecipientsForWorkspace(ctx context.Context, workspaceID int64) ([]ListRecipientsForWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipientsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipientsForWorkspaceRow{}
	for rows.Next() {
		var i ListRecipientsForWorkspaceRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ChatID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDigestTime = `-- name: SetDigestTime :exec
UPDATE telegram_settings SET digest_time = ? WHERE id = 1
`

func (q *Queries) SetDigestTime(ctx context.Context, digestTime string) error {
	_, err := q.db.ExecContext(ctx, setDigestTime, digestTime)
	return err
}

const setTelegramBotToken = `-- name: SetTelegramBotToken :exec
UPDATE telegram_settings SET bot_token = ? WHERE id = 1
`

func (q *Queries) SetTelegramBotToken(ctx context.Context, botToken string) error {
	_, err := q.db.ExecContext(ctx, setTelegramBotToken, botToken)
	return err
}

const unassignRecipientFromAccount = `-- name: UnassignRecipientFromAccount :exec
DELETE FROM account_recipients WHERE account_id = ? AND recipient_id = ?
`

type UnassignRecipientFromAccountParams struct {
	AccountID   int64
	RecipientID int64
}

func (q *Queries) UnassignRecipientFromAccount(ctx context.Context, arg UnassignRecipientFromAccountParams) error {
	_, err := q.db.ExecContext(ctx, unassignRecipientFromAccount, arg.AccountID, arg.RecipientID)
	return err
}

const unassignRecipientFromWorkspace = `-- name: UnassignRecipientFromWorkspace :exec
DELETE FROM workspace_recipients WHERE workspace_id = ? AND recipient_id = ?
`

type UnassignRecipientFromWorkspaceParams struct {
	WorkspaceID int64
	RecipientID int64
}

func (q *Queries) UnassignRecipientFromWorkspace(ctx context.Context, arg UnassignRecipientFromWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, unassignRecipientFromWorkspace, arg.WorkspaceID, arg.RecipientID)
	return err
}
