// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: triage.sql

package sqlcgen

import (
	"context"
)

const addFilterRule = `-- name: AddFilterRule :one
INSERT INTO filter_rules (account_id, kind, pattern, reason)
VALUES (?, ?, ?, ?)
RETURNING id, account_id, kind, pattern, reason, created_at
`

type AddFilterRuleParams struct {
	AccountID int64
	Kind      string
	Pattern   string
	Reason    string
}

func (q *Queries) AddFilterRule(ctx context.Context, arg AddFilterRuleParams) (FilterRule, error) {
	row := q.db.QueryRowContext(ctx, addFilterRule,
		arg.AccountID,
		arg.Kind,
		arg.Pattern,
		arg.Reason,
	)
	var i FilterRule
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Pattern,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const approveSender = `-- name: ApproveSender :exec
UPDATE senders SET screener_state = 'approved' WHERE id = ?
`

func (q *Queries) ApproveSender(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, approveSender, id)
	return err
}

const blockSender = `-- name: BlockSender :exec
UPDATE senders SET screener_state = 'blocked' WHERE id = ?
`

func (q *Queries) BlockSender(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, blockSender, id)
	return err
}

const deleteFilterRule = `-- name: DeleteFilterRule :exec
DELETE FROM filter_rules WHERE id = ?
`

func (q *Queries) DeleteFilterRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFilterRule, id)
	return err
}

const getSenderState = `-- name: GetSenderState :one
SELECT screener_state FROM senders WHERE account_id = ? AND address = ?
`

type GetSenderStateParams struct {
	AccountID int64
	Address   string
}

func (q *Queries) GetSenderState(ctx context.Context, arg GetSenderStateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSenderState, arg.AccountID, arg.Address)
	var screener_state string
	err := row.Scan(&screener_state)
	return screener_state, err
}

const listFilterRules = `-- name: ListFilterRules :many
SELECT id, account_id, kind, pattern, reason, created_at
FROM filter_rules WHERE account_id = ? ORDER BY id
`

func (q *Queries) ListFilterRules(ctx context.Context, accountID int64) ([]FilterRule, error) {
	rows, err := q.db.QueryContext(ctx, listFilterRules, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterRule{}
	for rows.Next() {
		var i FilterRule
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.Pattern,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPutAsideByWorkspace = `-- name: ListPutAsideByWorkspace :many
SELECT e.id, e.account_id, e.from_address, e.from_name, e.subject, e.received_at
FROM emails e
JOIN accounts a ON a.id = e.account_id
WHERE a.workspace_id = ? AND e.is_put_aside = 1
ORDER BY e.received_at DESC
`

type ListPutAsideByWorkspaceRow struct {
	ID          int64
	AccountID   int64
	FromAddress string
	FromName    string
	Subject     string
	ReceivedAt  string
}

func (q *Queries) ListPutAsideByWorkspace(ctx context.Context, workspaceID int64) ([]ListPutAsideByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listPutAsideByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPutAsideByWorkspaceRow{}
	for rows.Next() {
		var i ListPutAsideByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.FromAddress,
			&i.FromName,
			&i.Subject,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnscreenedByAccount = `-- name: ListUnscreenedByAccount :many
SELECT s.id AS sender_id, s.address, s.screener_state, s.first_seen_at,
       e.id AS email_id, e.subject, e.received_at
FROM senders s
JOIN emails e ON e.account_id = s.account_id AND e.from_address = s.address
WHERE s.account_id = ? AND s.screener_state = 'unscreened'
GROUP BY s.id
ORDER BY s.first_seen_at DESC
`

type ListUnscreenedByAccountRow struct {
	SenderID      int64
	Address       string
	ScreenerState string
	FirstSeenAt   string
	EmailID       int64
	Subject       string
	ReceivedAt    string
}

// Senders the screener hasn't decided on yet, with the email that prompted them.
func (q *Queries) ListUnscreenedByAccount(ctx context.Context, accountID int64) ([]ListUnscreenedByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnscreenedByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnscreenedByAccountRow{}
	for rows.Next() {
		var i ListUnscreenedByAccountRow
		if err := rows.Scan(
			&i.SenderID,
			&i.Address,
			&i.ScreenerState,
			&i.FirstSeenAt,
			&i.EmailID,
			&i.Subject,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSender = `-- name: UpsertSender :exec
INSERT INTO senders (account_id, address) VALUES (?, ?)
ON CONFLICT(account_id, address) DO NOTHING
`

type UpsertSenderParams struct {
	AccountID int64
	Address   string
}

func (q *Queries) UpsertSender(ctx context.Context, arg UpsertSenderParams) error {
	_, err := q.db.ExecContext(ctx, upsertSender, arg.AccountID, arg.Address)
	return err
}
