// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlcgen

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, emoji, sort_order)
VALUES (?, ?, COALESCE((SELECT MAX(sort_order) + 1 FROM workspaces), 0))
RETURNING id, name, emoji, sort_order, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name  string
	Emoji string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.Name, arg.Emoji)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, emoji, sort_order, created_at, updated_at
FROM workspaces
WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, emoji, sort_order, created_at, updated_at
FROM workspaces
ORDER BY sort_order, id
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Emoji,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderWorkspace = `-- name: ReorderWorkspace :exec
UPDATE workspaces SET sort_order = ?, updated_at = datetime('now') WHERE id = ?
`

type ReorderWorkspaceParams struct {
	SortOrder int64
	ID        int64
}

func (q *Queries) ReorderWorkspace(ctx context.Context, arg ReorderWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, reorderWorkspace, arg.SortOrder, arg.ID)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
UPDATE workspaces
SET name = ?, emoji = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWorkspaceParams struct {
	Name  string
	Emoji string
	ID    int64
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspace, arg.Name, arg.Emoji, arg.ID)
	return err
}
